<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>	
	</PropertyGroup>

	<ItemGroup>
		<None Remove="logo.jpg" />
		<None Remove="plugin.json" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\_build\release</OutputPath>
		<OutDir>$(OutputPath)</OutDir>
		<DefineConstants>TRACE;NOP_48</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>..\_build\debug</OutputPath>
		<OutDir>$(OutputPath)</OutDir>
		<DefineConstants>DEBUG;NOP_48</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\..\Common\Constants\Areas.cs" Link="Constants\Areas.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Common\Components\WidgetsProductNewProductViewComponent.cs" Link="Components\WidgetsProductNewProductComponent.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\Common\Content\NewProduct.css" Link="Content\NewProduct.css">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\..\Common\Content\NewProduct.css.map" Link="Content\NewProduct.css.map">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\..\Common\Content\NewProduct.less" Link="Content\NewProduct.less">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Include="..\..\Common\Content\NewProduct.min.css" Link="Content\NewProduct.min.css">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Common\Controllers\NewProductController.Admin.cs" Link="Controllers\NewProductController.Admin.cs" />
		<Compile Include="..\..\Common\Controllers\NewProductController.cs" Link="Controllers\NewProductController.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Common\Infrastructure\NopStartup.cs" Link="Infrastructure\NopStartup.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Common\Models\ConfigurationModel.cs" Link="Models\ConfigurationModel.cs" />
		<Compile Include="..\..\Common\Models\NewProductModel.cs" Link="Models\NewProductModel.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Common\Resources\ResourceNames.cs" Link="Resources\ResourceNames.cs" />
	</ItemGroup>

	<ItemGroup>

		<None Include="..\..\Common\Views\Shared\_AdminShared.cshtml" Link="Views\Shared\_AdminShared.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\..\Common\Views\Shared\_Shared.cshtml" Link="Views\Shared\_Shared.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Include="..\..\Common\Views\_ViewImports.cshtml" Link="Views\_ViewImports.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Include="..\..\Common\Views\Shared\Components\WidgetProductNewProduct\Default.cshtml" Link="Views\Shared\Components\WidgetProductNewProduct\Default.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Include="..\..\Common\Views\NewProduct\Configure.cshtml" Link="Views\NewProduct\Configure.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Include="..\..\Common\Views\NewProduct\PublicInfo.cshtml" Link="Views\NewProduct\PublicInfo.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Common\NewProductPlugin.cs" Link="NewProductPlugin.cs" />
		<Compile Include="..\..\Common\NewProductWidgetSettings.cs" Link="NewProductWidgetSettings.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="n:\nopCommerce 4.80\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj" />
		<ProjectReference Include="n:\nopCommerce 4.80\Presentation\Nop.Web\Nop.Web.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\..\logo.jpg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="plugin.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="nopLocalizationHelper" Version="0.8.1" GeneratePathProperty="true">
		</PackageReference>
	</ItemGroup>

	<Target Name="Copy reference" AfterTargets="CoreCompile">
		<Copy
			SourceFiles="$(PkgnopLocalizationHelper)\lib\net8.0\nopLocalizationHelper.dll"
			DestinationFolder="$(OutDir)" />
	</Target>
	<PropertyGroup>
		<!-- this in combination with GeneratePathProperty allows us to let the build helper copy the file for packaging -->
		<nopLocRef Condition=" '$(nopLocRef)' == '' ">$(PkgnopLocalizationHelper)\lib\net8.0\nopLocalizationHelper.dll</nopLocRef>
	</PropertyGroup>

	<ItemGroup>
		<None Update="Views\NewProduct\Configure.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Content\NewProduct.css">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Content\NewProduct.css.map">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Content\NewProduct.less">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="Content\NewProduct.min.css">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Views\NewProduct\PublicInfo.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Views\NewProduct\ProductAddPopup.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Views\Shared\_AdminShared.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Views\Shared\_Shared.cshtml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<!-- This target execute after "Build" target -->
	<Target Name="NopTarget" AfterTargets="Build">
		<!-- Delete unnecessary libraries from plugins path -->
		<MSBuild Projects="n:\nopCommerce 4.80\Build\ClearPluginAssemblies.proj" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />
	</Target>
	<Target Name="FilterCopyLocalItems" AfterTargets="ResolveLockFileCopyLocalProjectDeps">
		<ItemGroup>
			<ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)' != 'nopLocalizationHelper'" />
		</ItemGroup>
	</Target>
</Project>